### PR TITLE
Fix input item

### PR DESCRIPTION
**Pull request by to0simple**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd-mobile/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by to0simple** [comment]
#574

**Comment by to0simple** [comment]
inputItem控件实现setDisabledState()方法 #574

**Comment by Mr-Eve** [comment]
@fisherspy codecov/project显示失败的, 这个怎么处理?

**Comment by fisherspy** [comment]
> @fisherspy codecov/project显示失败的, 这个怎么处理?

应该编译有问题，需要关闭重新提交PR

**Pull request closed without merging**
